// <auto-generated />
using System;
using Kontrer.OwnerServer.OrderService.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kontrer.OwnerServer.OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderServiceDbContext))]
    [Migration("20211106215918_sync")]
    partial class sync
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.AccommodationOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerPrivateNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.AccommodationOrderEntity", b =>
                {
                    b.OwnsOne("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.AccommodationRequirement", "Requirment", b1 =>
                        {
                            b1.Property<int>("AccommodationOrderEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<DateTime>("From")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("To")
                                .HasColumnType("datetime2");

                            b1.HasKey("AccommodationOrderEntityId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("AccommodationOrderEntityId");

                            b1.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.DiscountBlueprint", "Discounts", b2 =>
                                {
                                    b2.Property<int>("AccommodationRequirementAccommodationOrderEntityId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<int?>("DiscountId")
                                        .HasColumnType("int");

                                    b2.Property<string>("DiscountName")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool>("IsPercentageDiscount")
                                        .HasColumnType("bit");

                                    b2.Property<float>("PercentageDiscount")
                                        .HasColumnType("real");

                                    b2.HasKey("AccommodationRequirementAccommodationOrderEntityId", "Id");

                                    b2.ToTable("Orders_Discounts");

                                    b2.WithOwner()
                                        .HasForeignKey("AccommodationRequirementAccommodationOrderEntityId");

                                    b2.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "AmountDiscount", b3 =>
                                        {
                                            b3.Property<int>("DiscountBlueprintAccommodationRequirementAccommodationOrderEntityId")
                                                .HasColumnType("int");

                                            b3.Property<int>("DiscountBlueprintId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<decimal>("Amount")
                                                .HasColumnType("decimal(18,2)");

                                            b3.Property<int>("Currency")
                                                .HasColumnType("int");

                                            b3.HasKey("DiscountBlueprintAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintId");

                                            b3.ToTable("Orders_Discounts");

                                            b3.WithOwner()
                                                .HasForeignKey("DiscountBlueprintAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintId");
                                        });

                                    b2.Navigation("AmountDiscount");
                                });

                            b1.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.ItemRequirement", "AccommodationItems", b2 =>
                                {
                                    b2.Property<int>("AccommodationRequirementAccommodationOrderEntityId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<bool>("CanParentApplyDiscount")
                                        .HasColumnType("bit");

                                    b2.Property<int>("Count")
                                        .HasColumnType("int");

                                    b2.Property<int?>("ItemId")
                                        .HasColumnType("int");

                                    b2.Property<string>("ItemName")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<float>("TaxPercentageToAdd")
                                        .HasColumnType("real");

                                    b2.HasKey("AccommodationRequirementAccommodationOrderEntityId", "Id");

                                    b2.ToTable("Orders_AccommodationItems");

                                    b2.WithOwner()
                                        .HasForeignKey("AccommodationRequirementAccommodationOrderEntityId");

                                    b2.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.DiscountBlueprint", "Discounts", b3 =>
                                        {
                                            b3.Property<int>("ItemRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                .HasColumnType("int");

                                            b3.Property<int>("ItemRequirementId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<int?>("DiscountId")
                                                .HasColumnType("int");

                                            b3.Property<string>("DiscountName")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool>("IsPercentageDiscount")
                                                .HasColumnType("bit");

                                            b3.Property<float>("PercentageDiscount")
                                                .HasColumnType("real");

                                            b3.HasKey("ItemRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementId", "Id");

                                            b3.ToTable("Orders_AccommodationItems_Discounts");

                                            b3.WithOwner()
                                                .HasForeignKey("ItemRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementId");

                                            b3.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "AmountDiscount", b4 =>
                                                {
                                                    b4.Property<int>("DiscountBlueprintItemRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("DiscountBlueprintItemRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("DiscountBlueprintId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("int")
                                                        .UseIdentityColumn();

                                                    b4.Property<decimal>("Amount")
                                                        .HasColumnType("decimal(18,2)");

                                                    b4.Property<int>("Currency")
                                                        .HasColumnType("int");

                                                    b4.HasKey("DiscountBlueprintItemRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintItemRequirementId", "DiscountBlueprintId");

                                                    b4.ToTable("Orders_AccommodationItems_Discounts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("DiscountBlueprintItemRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintItemRequirementId", "DiscountBlueprintId");
                                                });

                                            b3.Navigation("AmountDiscount");
                                        });

                                    b2.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "CostPerOne", b3 =>
                                        {
                                            b3.Property<int>("ItemRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                .HasColumnType("int");

                                            b3.Property<int>("ItemRequirementId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<decimal>("Amount")
                                                .HasColumnType("decimal(18,2)");

                                            b3.Property<int>("Currency")
                                                .HasColumnType("int");

                                            b3.HasKey("ItemRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementId");

                                            b3.ToTable("Orders_AccommodationItems");

                                            b3.WithOwner()
                                                .HasForeignKey("ItemRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementId");
                                        });

                                    b2.Navigation("CostPerOne");

                                    b2.Navigation("Discounts");
                                });

                            b1.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.RoomRequirement", "Rooms", b2 =>
                                {
                                    b2.Property<int>("AccommodationRequirementAccommodationOrderEntityId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<DateTime>("RoomEndDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("RoomStartDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("RoomType")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AccommodationRequirementAccommodationOrderEntityId", "Id");

                                    b2.ToTable("RoomRequirement");

                                    b2.WithOwner()
                                        .HasForeignKey("AccommodationRequirementAccommodationOrderEntityId");

                                    b2.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.DiscountBlueprint", "Discounts", b3 =>
                                        {
                                            b3.Property<int>("RoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                .HasColumnType("int");

                                            b3.Property<int>("RoomRequirementId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<int?>("DiscountId")
                                                .HasColumnType("int");

                                            b3.Property<string>("DiscountName")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool>("IsPercentageDiscount")
                                                .HasColumnType("bit");

                                            b3.Property<float>("PercentageDiscount")
                                                .HasColumnType("real");

                                            b3.HasKey("RoomRequirementAccommodationRequirementAccommodationOrderEntityId", "RoomRequirementId", "Id");

                                            b3.ToTable("RoomRequirement_Discounts");

                                            b3.WithOwner()
                                                .HasForeignKey("RoomRequirementAccommodationRequirementAccommodationOrderEntityId", "RoomRequirementId");

                                            b3.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "AmountDiscount", b4 =>
                                                {
                                                    b4.Property<int>("DiscountBlueprintRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("DiscountBlueprintRoomRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("DiscountBlueprintId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("int")
                                                        .UseIdentityColumn();

                                                    b4.Property<decimal>("Amount")
                                                        .HasColumnType("decimal(18,2)");

                                                    b4.Property<int>("Currency")
                                                        .HasColumnType("int");

                                                    b4.HasKey("DiscountBlueprintRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintRoomRequirementId", "DiscountBlueprintId");

                                                    b4.ToTable("RoomRequirement_Discounts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("DiscountBlueprintRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintRoomRequirementId", "DiscountBlueprintId");
                                                });

                                            b3.Navigation("AmountDiscount");
                                        });

                                    b2.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.ItemRequirement", "RoomItems", b3 =>
                                        {
                                            b3.Property<int>("RoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                .HasColumnType("int");

                                            b3.Property<int>("RoomRequirementId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<bool>("CanParentApplyDiscount")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Count")
                                                .HasColumnType("int");

                                            b3.Property<int?>("ItemId")
                                                .HasColumnType("int");

                                            b3.Property<string>("ItemName")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<float>("TaxPercentageToAdd")
                                                .HasColumnType("real");

                                            b3.HasKey("RoomRequirementAccommodationRequirementAccommodationOrderEntityId", "RoomRequirementId", "Id");

                                            b3.ToTable("RoomRequirement_RoomItems");

                                            b3.WithOwner()
                                                .HasForeignKey("RoomRequirementAccommodationRequirementAccommodationOrderEntityId", "RoomRequirementId");

                                            b3.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.DiscountBlueprint", "Discounts", b4 =>
                                                {
                                                    b4.Property<int>("ItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("ItemRequirementRoomRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("ItemRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("Id")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("int")
                                                        .UseIdentityColumn();

                                                    b4.Property<int?>("DiscountId")
                                                        .HasColumnType("int");

                                                    b4.Property<string>("DiscountName")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<bool>("IsPercentageDiscount")
                                                        .HasColumnType("bit");

                                                    b4.Property<float>("PercentageDiscount")
                                                        .HasColumnType("real");

                                                    b4.HasKey("ItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementRoomRequirementId", "ItemRequirementId", "Id");

                                                    b4.ToTable("RoomRequirement_RoomItems_Discounts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementRoomRequirementId", "ItemRequirementId");

                                                    b4.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "AmountDiscount", b5 =>
                                                        {
                                                            b5.Property<int>("DiscountBlueprintItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("DiscountBlueprintItemRequirementRoomRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("DiscountBlueprintItemRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("DiscountBlueprintId")
                                                                .ValueGeneratedOnAdd()
                                                                .HasColumnType("int")
                                                                .UseIdentityColumn();

                                                            b5.Property<decimal>("Amount")
                                                                .HasColumnType("decimal(18,2)");

                                                            b5.Property<int>("Currency")
                                                                .HasColumnType("int");

                                                            b5.HasKey("DiscountBlueprintItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintItemRequirementRoomRequirementId", "DiscountBlueprintItemRequirementId", "DiscountBlueprintId");

                                                            b5.ToTable("RoomRequirement_RoomItems_Discounts");

                                                            b5.WithOwner()
                                                                .HasForeignKey("DiscountBlueprintItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintItemRequirementRoomRequirementId", "DiscountBlueprintItemRequirementId", "DiscountBlueprintId");
                                                        });

                                                    b4.Navigation("AmountDiscount");
                                                });

                                            b3.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "CostPerOne", b4 =>
                                                {
                                                    b4.Property<int>("ItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("ItemRequirementRoomRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("ItemRequirementId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("int")
                                                        .UseIdentityColumn();

                                                    b4.Property<decimal>("Amount")
                                                        .HasColumnType("decimal(18,2)");

                                                    b4.Property<int>("Currency")
                                                        .HasColumnType("int");

                                                    b4.HasKey("ItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementRoomRequirementId", "ItemRequirementId");

                                                    b4.ToTable("RoomRequirement_RoomItems");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ItemRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementRoomRequirementId", "ItemRequirementId");
                                                });

                                            b3.Navigation("CostPerOne");

                                            b3.Navigation("Discounts");
                                        });

                                    b2.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.PersonRequirement", "People", b3 =>
                                        {
                                            b3.Property<int>("RoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                .HasColumnType("int");

                                            b3.Property<int>("RoomRequirementId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<int>("PersonType")
                                                .HasColumnType("int");

                                            b3.HasKey("RoomRequirementAccommodationRequirementAccommodationOrderEntityId", "RoomRequirementId", "Id");

                                            b3.ToTable("PersonRequirement");

                                            b3.WithOwner()
                                                .HasForeignKey("RoomRequirementAccommodationRequirementAccommodationOrderEntityId", "RoomRequirementId");

                                            b3.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.DiscountBlueprint", "Discounts", b4 =>
                                                {
                                                    b4.Property<int>("PersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("PersonRequirementRoomRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("PersonRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("Id")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("int")
                                                        .UseIdentityColumn();

                                                    b4.Property<int?>("DiscountId")
                                                        .HasColumnType("int");

                                                    b4.Property<string>("DiscountName")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<bool>("IsPercentageDiscount")
                                                        .HasColumnType("bit");

                                                    b4.Property<float>("PercentageDiscount")
                                                        .HasColumnType("real");

                                                    b4.HasKey("PersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "PersonRequirementRoomRequirementId", "PersonRequirementId", "Id");

                                                    b4.ToTable("PersonRequirement_Discounts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("PersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "PersonRequirementRoomRequirementId", "PersonRequirementId");

                                                    b4.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "AmountDiscount", b5 =>
                                                        {
                                                            b5.Property<int>("DiscountBlueprintPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("DiscountBlueprintPersonRequirementRoomRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("DiscountBlueprintPersonRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("DiscountBlueprintId")
                                                                .ValueGeneratedOnAdd()
                                                                .HasColumnType("int")
                                                                .UseIdentityColumn();

                                                            b5.Property<decimal>("Amount")
                                                                .HasColumnType("decimal(18,2)");

                                                            b5.Property<int>("Currency")
                                                                .HasColumnType("int");

                                                            b5.HasKey("DiscountBlueprintPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintPersonRequirementRoomRequirementId", "DiscountBlueprintPersonRequirementId", "DiscountBlueprintId");

                                                            b5.ToTable("PersonRequirement_Discounts");

                                                            b5.WithOwner()
                                                                .HasForeignKey("DiscountBlueprintPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintPersonRequirementRoomRequirementId", "DiscountBlueprintPersonRequirementId", "DiscountBlueprintId");
                                                        });

                                                    b4.Navigation("AmountDiscount");
                                                });

                                            b3.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.ItemRequirement", "PersonItems", b4 =>
                                                {
                                                    b4.Property<int>("PersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("PersonRequirementRoomRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("PersonRequirementId")
                                                        .HasColumnType("int");

                                                    b4.Property<int>("Id")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("int")
                                                        .UseIdentityColumn();

                                                    b4.Property<bool>("CanParentApplyDiscount")
                                                        .HasColumnType("bit");

                                                    b4.Property<int>("Count")
                                                        .HasColumnType("int");

                                                    b4.Property<int?>("ItemId")
                                                        .HasColumnType("int");

                                                    b4.Property<string>("ItemName")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<float>("TaxPercentageToAdd")
                                                        .HasColumnType("real");

                                                    b4.HasKey("PersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "PersonRequirementRoomRequirementId", "PersonRequirementId", "Id");

                                                    b4.ToTable("PersonRequirement_PersonItems");

                                                    b4.WithOwner()
                                                        .HasForeignKey("PersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "PersonRequirementRoomRequirementId", "PersonRequirementId");

                                                    b4.OwnsMany("Kontrer.OwnerServer.OrderService.Domain.Orders.AccommodationOrder.ValueObjects.Requirements.DiscountBlueprint", "Discounts", b5 =>
                                                        {
                                                            b5.Property<int>("ItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("ItemRequirementPersonRequirementRoomRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("ItemRequirementPersonRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("ItemRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("Id")
                                                                .ValueGeneratedOnAdd()
                                                                .HasColumnType("int")
                                                                .UseIdentityColumn();

                                                            b5.Property<int?>("DiscountId")
                                                                .HasColumnType("int");

                                                            b5.Property<string>("DiscountName")
                                                                .HasColumnType("nvarchar(max)");

                                                            b5.Property<bool>("IsPercentageDiscount")
                                                                .HasColumnType("bit");

                                                            b5.Property<float>("PercentageDiscount")
                                                                .HasColumnType("real");

                                                            b5.HasKey("ItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementPersonRequirementRoomRequirementId", "ItemRequirementPersonRequirementId", "ItemRequirementId", "Id");

                                                            b5.ToTable("PersonRequirement_PersonItems_Discounts");

                                                            b5.WithOwner()
                                                                .HasForeignKey("ItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementPersonRequirementRoomRequirementId", "ItemRequirementPersonRequirementId", "ItemRequirementId");

                                                            b5.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "AmountDiscount", b6 =>
                                                                {
                                                                    b6.Property<int>("DiscountBlueprintItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                                        .HasColumnType("int");

                                                                    b6.Property<int>("DiscountBlueprintItemRequirementPersonRequirementRoomRequirementId")
                                                                        .HasColumnType("int");

                                                                    b6.Property<int>("DiscountBlueprintItemRequirementPersonRequirementId")
                                                                        .HasColumnType("int");

                                                                    b6.Property<int>("DiscountBlueprintItemRequirementId")
                                                                        .HasColumnType("int");

                                                                    b6.Property<int>("DiscountBlueprintId")
                                                                        .ValueGeneratedOnAdd()
                                                                        .HasColumnType("int")
                                                                        .UseIdentityColumn();

                                                                    b6.Property<decimal>("Amount")
                                                                        .HasColumnType("decimal(18,2)");

                                                                    b6.Property<int>("Currency")
                                                                        .HasColumnType("int");

                                                                    b6.HasKey("DiscountBlueprintItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintItemRequirementPersonRequirementRoomRequirementId", "DiscountBlueprintItemRequirementPersonRequirementId", "DiscountBlueprintItemRequirementId", "DiscountBlueprintId");

                                                                    b6.ToTable("PersonRequirement_PersonItems_Discounts");

                                                                    b6.WithOwner()
                                                                        .HasForeignKey("DiscountBlueprintItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "DiscountBlueprintItemRequirementPersonRequirementRoomRequirementId", "DiscountBlueprintItemRequirementPersonRequirementId", "DiscountBlueprintItemRequirementId", "DiscountBlueprintId");
                                                                });

                                                            b5.Navigation("AmountDiscount");
                                                        });

                                                    b4.OwnsOne("Kontrer.Shared.Models.Pricing.Cash", "CostPerOne", b5 =>
                                                        {
                                                            b5.Property<int>("ItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("ItemRequirementPersonRequirementRoomRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("ItemRequirementPersonRequirementId")
                                                                .HasColumnType("int");

                                                            b5.Property<int>("ItemRequirementId")
                                                                .ValueGeneratedOnAdd()
                                                                .HasColumnType("int")
                                                                .UseIdentityColumn();

                                                            b5.Property<decimal>("Amount")
                                                                .HasColumnType("decimal(18,2)");

                                                            b5.Property<int>("Currency")
                                                                .HasColumnType("int");

                                                            b5.HasKey("ItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementPersonRequirementRoomRequirementId", "ItemRequirementPersonRequirementId", "ItemRequirementId");

                                                            b5.ToTable("PersonRequirement_PersonItems");

                                                            b5.WithOwner()
                                                                .HasForeignKey("ItemRequirementPersonRequirementRoomRequirementAccommodationRequirementAccommodationOrderEntityId", "ItemRequirementPersonRequirementRoomRequirementId", "ItemRequirementPersonRequirementId", "ItemRequirementId");
                                                        });

                                                    b4.Navigation("CostPerOne");

                                                    b4.Navigation("Discounts");
                                                });

                                            b3.Navigation("Discounts");

                                            b3.Navigation("PersonItems");
                                        });

                                    b2.Navigation("Discounts");

                                    b2.Navigation("People");

                                    b2.Navigation("RoomItems");
                                });

                            b1.Navigation("AccommodationItems");

                            b1.Navigation("Discounts");

                            b1.Navigation("Rooms");
                        });

                    b.Navigation("Requirment");
                });
#pragma warning restore 612, 618
        }
    }
}
