apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: "localhost:6379" #localhost:6379 [redis.address]
  - name: redisPassword
    value: ""
#auth:
 # secretStore: localsecretstore